### ISSUE TITLE
Fluent interface

### ISSUE THREAD

**Issue by PiNotEqual3** [sebastiaanluca/php-pipe-operator#6]
I do love the fluent code but wouldn't it be better to write a fluent interface? It would eliminate the need for PIPED_VALUE.

For example see the fluent strings in Laravel:
https://laravel.com/docs/8.x/helpers#fluent-strings

You could do the same for arrays and others.

Am I missing something?

**Comment by sebastiaanluca** [comment]
Can you give a literal example of the fluent interface you mean?

The difference vs Laravel string helpers for instance, is that those methods are custom and can be predefined. Whereas for this package, you can call *any* PHP method. So we can't write an interface for that —to provide autocompletion for instance— without defining *every* PHP method there is.

> It would eliminate the need for PIPED_VALUE.

The reason we have the proxy class and `PIPED_VALUE` is the same as above: we don't have control over how these functions' signatures are written and these can vary wildly. For one function the piped value comes first, for another it's last or second or third. So `PIPED_VALUE` is there so you can choose yourself as which parameter the piped value should be passed, similar to the original RFC (`$$` was used there).

Hope that answers some things. Always open to suggestions to improve this package.

**Comment by PiNotEqual3** [comment]
Yes, I meant defining every PHP (string) method.

I know that is quite some work but it might be worth it.
We have to do it only once.

**Comment by sebastiaanluca** [comment]
That's *a lot* of work and not manageable to keep up with. It's not just every string method, but every single PHP method and every change, every release. Maybe there's another way, but closing for now.
